export default [
  {
    unit: "MND-N",
    class: "cards__card cards__card__div cards__card__div_mndn",
    com: "BGEN Krzysztof Skoczylas",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
  {
    unit: "MND-N",
    class: "cards__card cards__card__div cards__card__div_mndne",
    com: "BGEN Marek Wrona",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndne.pl">mndn.pl</a>,
  },
  {
    unit: "NFIU EST",
    class: "cards__card cards__card__nfiu__est",
    com: "BGEN Jan Kusso",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
  {
    unit: "NFIU LTU",
    class: "cards__card cards__card__nfiu__ltu",
    com: "BGEN Jan Kusso",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
  {
    unit: "NFIU LVA",
    class: "cards__card cards__card__nfiu__lva",
    com: "BGEN Jan Kusso",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
  {
    unit: "NFIU POL",
    class: "cards__card cards__card__nfiu__pol",
    com: "BGEN Jan Kusso",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
  {
    unit: "CSB",
    class: "cards__card cards__card__csb",
    com: "BGEN Jan Kusso",
    email: "mndn@army.com",
    phone: "+48 11 111 1111",
    web: <a href="mndn.pl">mndn.pl</a>,
  },
];
